### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ubiot-alejandro** [radpointhq/orthanc-s3-storage#10]
Hi Radpoint team, more than an issue, i want to ask you about an specific step in this integration.

I successfully complete the build (scripts/docker-build-orthanc) of the plugin, now i'm trying to do the run (scripts/docker-run-orthanc)

![image](https://user-images.githubusercontent.com/41581013/72459682-a96d5b00-37a1-11ea-96bc-f5e820baaaaf.png)

I already update the orthanc.json file, now i should copy the plugin and the libraries but i don't know where they are. Where they should be?

My apologizes if this is a silly question but i'm new and i'm trying to build a docker image of Orthanc with this plugin.

**Comment by ubiot-alejandro** [comment]
I already made it work! My apologies for the inconvenience.

**Comment by bpycinski** [comment]
That's great it worked, good luck! :)

**Comment by kwach** [comment]
If it is unclear from the README.md, would you consider describing it better there?

Cheers,
M.

**Comment by ubiot-alejandro** [comment]
Yeah, i 'll edit the file explaining better just the part when i was
confused, for beginners.
It's a pleasure for my to contribute.
