### ISSUE TITLE
Dicom attachments cannot be stored

### ISSUE THREAD

**Issue by amcgowan-frozenmountain** [radpointhq/orthanc-s3-storage#11]
User defined attachments are not handled by the S3 plugin. 

I configured a user defined attachment to store a base64 preview image:

Orthanc.json
```  
// Dictionary of symbolic names for the user-defined types of
  // attached files. Each entry must map an unique string to an unique
  // number between 1024 and 65535. Optionally, a second argument can
  // provided to specify a MIME content type for the attachment.
  "UserContentType" : {
    // "sample" : 1024
    // "sample2" : [ 1025, "application/pdf" ]
	"jpegBase64": [ 14000, "text/plain" ]
  },
```
On **PUT** `/instances/{instanceId}/attachments/jpegBase64/` I end up with a 500 error: 
` Error in the plugin implementing a custom storage area`

Source is from: `E0422 21:26:03.319931 PluginsManager.cpp:164] [S3] Never should happen`

Which I believe is coming from https://github.com/radpointhq/orthanc-s3-storage/blob/4a5afb69e723efcb086ae91bf1a9c3ea6964d76f/src/Plugin.cpp#L97

**Comment by bpycinski** [comment]
Hello @amcgowan-frozenmountain, you are right, storage of attachments was not implemented. Hovewer, if you want to store all the files in S3, please try this branch: https://github.com/radpointhq/orthanc-s3-storage/tree/store-everything-on-s3 .

**Comment by amcgowan-frozenmountain** [comment]
@bpycinski Thanks, that looks like it will do what I need. Any idea why that check was originally put in place? My initial thought when I saw the code was that there was some other underlying reason why only the dicom file would be allowed through to S3.

**Comment by bpycinski** [comment]
The issue was resolved in branch [store-everything-on-s3](https://github.com/radpointhq/orthanc-s3-storage/tree/store-everything-on-s3).

**Comment by wkoszek** [comment]
@bpycinski Any plans to merge store-everything-on-s3 @2018denjasa and I were wondering

**Comment by bpycinski** [comment]
@wkoszek, I have merged the branch. If you experienced troubles with missing libssl, see #12 for a solution.

**Comment by wkoszek** [comment]
@bpycinski Thanks. We will try it out and report any issues.
