### ISSUE TITLE
Error while loading shared libraries

### ISSUE THREAD

**Issue by SamJBentley** [radpointhq/orthanc-s3-storage#12]
Hi,
I've followed the instructions on how to build and run in Docker. When I run the `run-orthanc-in-docker.sh` script, I get the following error:

`Orthanc: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory`

If I look in the container, I can see that there is a /usr/lib/x86_64-linux-gnu/libssl.so.1.1 library, but not the 1.0.0 version that is expected.

**Comment by bpycinski** [comment]
Hi, indeed, it look like Osimis has finally ugraded their Orthanc image. You can try with an older version, eg. `osimis/orthanc:19.10.3` should be fine (in `scripts/docker-run-orthanc/Dockerfile`). Moreover, you can set a fixed version of AWS (e.g.  `SET(AWS_SDK_VERSION "1.7.296")` in `Resources/CMake/AwsSdkConfiguration.cmake`).

**Comment by SamJBentley** [comment]
Great, the older version is working - thanks for such a quick response!

**Comment by bpycinski** [comment]
Hi, good, could you please create a pull request with the versions that are for sure working?

**Comment by SamJBentley** [comment]
Sure, although I keep getting a 403 error when pushing my local branch. Can you create a branch I can commit to please?

**Comment by bpycinski** [comment]
Yeah, it is because you need to fork the repo first, here you have permissions for pushing and then you create pull request (we pull your changes). There are lots of manuals about it, for example at github docs: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by marns** [comment]
Has anyone gotten this working with a current version of Orthanc, or alongside the default plugins build?

**Comment by septianw** [comment]
> Has anyone gotten this working with a current version of Orthanc, or alongside the default plugins build?

i'm able to make it work by change Dockerfile of docker-build from ubuntu to debian:buster-slim

**Comment by marns** [comment]
Fantastic! Works with jodogne/orthanc-plugins too. Thanks!

**Comment by bpycinski** [comment]
The master branch was updated and it inherits `debian:buster-slim` now. Thanks @septianw for your advice.
