### ISSUE TITLE
No reply from curling remote AWS EC2 server

### ISSUE THREAD

**Issue by Signo-Alaris** [radpointhq/orthanc-s3-storage#16]
Hi guys,

Thanks a lot for developing this, it is great to have this plugin, but unfortunately for me, I can only contact it with localhost. I launched an AWS EC2 Ubuntu 18 LTS instance and built and ran the docker image with no problems. I can SSH into the instance and run `curl http://localhost:8042/instances` and it works as expected, returning any instances that I have stored(again, while only using localhost).

However, if I use the public IP instead of localhost e.g. `curl http://X.X.X.X:8042/instances`, nothing is returned. I'm using the run-orthanc-in-docker.sh to launch the container so it's using the host network adapter. I've looked through tutorials online about launching a docker image in EC2 and accessing it via public IP and there's no indication the problem would be on AWS's side.

Any help at all is appreciated.

**Comment by bpycinski** [comment]
Hi, sorry for very late response, I hope you have found the solution for your problem. It looks not related to the plugin itself, but to the docker or network setup.
