### ISSUE TITLE
docker run

### ISSUE THREAD

**Issue by zhangfanshcn** [radpointhq/orthanc-s3-storage#2]
At the last step(docker run):
sudo docker run --rm \
-v /home/ubuntu/orthanc/orthanc.json:/etc/orthanc/orthanc.json:ro \
-v /home/ubuntu/orthanc/log/:/var/log/orthanc/ \
-v /home/ubuntu/orthanc/orthanc-db/:/var/lib/orthanc/db/ \
-v /home/ubuntu/orthanc/lib:/usr/local/lib \
-v /home/ubuntu/orthanc/plugins:/usr/local/share/orthanc/plugins \
-v /home/ubuntu/orthanc/scripts:/etc/orthanc/scripts \
-e LD_LIBRARY_PATH=/usr/local/lib \
-p 4242:4242 \
-p 8042:8042 \
jodogne/orthanc

I get some error:

Orthanc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/lib/libstdc++.so.6)
Orthanc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.18' not found (required by /usr/local/lib/libstdc++.so.6)
Orthanc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.17' not found (required by /usr/local/lib/libstdc++.so.6)

**Comment by bpycinski** [comment]
Hello,
thank you for your report. After recent upgrade of `jodogne/orthanc` (now it is based on Debian, not Ubuntu), there is no need to update glibc. Unfortunately, the plugin doesn't work with this Docker image, because it does not have libcurl. We are working on a solution and we will update sources as soon as possible.
Greetings
Bartłomiej

**Comment by pkat** [comment]
Hi all,
I'm having similar issues when attempting to compile the plugin. I am attempting to use the `osimis/orthanc` docker image. It would be great to understand what dependencies are required and how to validate a successful build of the plugin. I'll try to post the errors I'm seeing when I get a chance to attempt the build again.
Also, is there any information regarding the overall performance of this plugin?
Thanks,
Prashant

**Comment by bpycinski** [comment]
Hi, the repository has been updated. Build process has been simplified much.

**Comment by pkat** [comment]
HI @bpycinski, I've pulled the latest and was able to successfully compile the plugin. 
However when running with orthanc on docker on ec2 I get the following:
```
orthanc_1     | I0221 20:59:41.769723 PluginsManager.cpp:288] Scanning folder /usr/share/orthanc/plugins for plugins
orthanc_1     | I0221 20:59:41.769790 PluginsManager.cpp:311] Found a shared library: "/usr/share/orthanc/plugins/libOrthancS3StoragePlugin.so"
orthanc_1     | W0221 20:59:41.796344 PluginsManager.cpp:269] Registering plugin 's3-storage' (version 1.4.0-0.2.1)
orthanc_1     | W0221 20:59:41.796390 PluginsManager.cpp:168] [S3] Storage plugin is initializing
orthanc_1     | T0221 20:59:41.796403 OrthancPlugins.cpp:3489] Calling service 7 from plugin /usr/share/orthanc/plugins/libOrthancS3StoragePlugin.so
orthanc_1     | T0221 20:59:41.796418 OrthancPlugins.cpp:3489] Calling service 13 from plugin /usr/share/orthanc/plugins/libOrthancS3StoragePlugin.so
orthanc_1     | T0221 20:59:41.796825 OrthancPlugins.cpp:3489] Calling service 13 from plugin /usr/share/orthanc/plugins/libOrthancS3StoragePlugin.so
orthanc_1     | I0221 20:59:41.797273 PluginsManager.cpp:172] [S3] Aws region: us-east-1
orthanc_1     | I0221 20:59:41.797294 PluginsManager.cpp:172] [S3] Aws bucket: <bucket_name_replaced>
orthanc_1     | I0221 20:59:41.797316 PluginsManager.cpp:172] [S3] S3Direct
orthanc_1     | I0221 20:59:41.797871 PluginsManager.cpp:172] No credentials in the config file. Falling back to ~/.aws/credentials or env variables.
orthanc_1     | I0221 20:59:41.798218 PluginsManager.cpp:172] [S3] Checking bucket: <bucket_name_replaced>
orthanc_1     | E0221 21:00:07.390628 PluginsManager.cpp:164] [S3] Create Bucket error:  Unable to connect to endpoint
orthanc_1     | E0221 21:00:07.390677 PluginsManager.cpp:102] Error while initializing plugin /usr/share/orthanc/plugins/libOrthancS3StoragePlugin.so (code 1)
orthanc_1     | E0221 21:00:07.392019 main.cpp:1462] Uncaught exception, stopping now: [Error while using a shared library (plugin)] (code 25)
orthanc_1     | W0221 21:00:07.392302 main.cpp:1495] Orthanc has stopped
```
I've ensured that aws credentials are correct and have the right permissions. I have defined them both as part of the config as well as env vars.

Any ideas on whats happening or how to resolve? I'm assuming that this is related to either the aws-sdk or libcurl

**Comment by kwach** [comment]
This looks like mixed up versions of curl library. Notice that AWS SDK pulls one from the OS and building Orthnac stuff you need to do the same.
