### ISSUE TITLE
Upstream bug(s) in Orthanc building process.

### ISSUE THREAD

**Issue by TZubiri** [radpointhq/orthanc-s3-storage#3]
This is a report of an upstream bug in the building process of Orthanc.
```

Using local copy of: http://www.orthanc-server.com/downloads/third-party/orthanc-framework/Orthanc-1.4.0.tar.gz
Using libiconv
Switching to C++11 standard in gcc/clang, as version of JsonCpp is >= 1.0.0
Switching to C++11 standard in gcc/clang, as version of JsonCpp is >= 1.0.0
Using local copy of http://www.orthanc-server.com/downloads/third-party/openssl-1.0.2o.tar.gz
CMake Error at build/Orthanc-1.4.0/Resources/CMake/DownloadPackage.cmake:87 (message):
  The MD5 hash of a previously download file is invalid:
  /app/ThirdPartyDownloads/openssl-1.0.2o.tar.gz
Call Stack (most recent call first):
  build/Orthanc-1.4.0/Resources/CMake/OpenSslConfiguration.cmake:12 (DownloadPackage)
  CMakeLists.txt:64 (include)


-- Configuring incomplete, errors occurred!
See also "/app/build/CMakeFiles/CMakeOutput.log".
See also "/app/build/CMakeFiles/CMakeError.log".
cmake error.

```
I am making an issue report here because I had trouble consuming the plugin. I encountered this bug as a consumer, and while I may have encountered this bug while building Orthanc as well, (as a developer), Orthanc packaged its product for Docker and local execution in such a way that I didn't encounter this bug.

The technical explanation for this bug is that my third world internet connection was slow enough to trigger a timeout defensive programming guard written in the build's CMAKE files at https://bitbucket.org/sjodogne/orthanc/src/b88937ef597b33c4387a546c751827019bcdc205/Resources/CMake/DownloadPackage.cmake?at=default&fileviewer=file-view-default , the solution is to either clear the cache with the partially downloaded file and increase the timeout until it downloads succesfully, or to switch to a faster connection. This information is only useful to people who land on this page by googling this error (either by trying to consume this plugin or building Orthanc), so at least we leave a useful artifact through this issue.

But the root issue here is that I am building Orthanc in order to consume the plugin. Something I didn't need to do with other Orthanc plugins, (or even Orthanc itself) so maybe the solution would entail packaging the pluging and distributing a release version. Did I miss an easier way to consume the plugin?

I will continue trying to build the plugin. I would appreciate a sanity check on this. 
Thank you for your time and for open sourcing this product.

--

Tomas Zubiri
Data Engineer at JC imagenes
me@tomaszubiri.com

**Comment by TZubiri** [comment]
Stumbled upon an error in the plugin's build process (file: docker-build-orthanc./docker-run-image.sh ):

```
Including /app/build/Orthanc-1.4.0/Resources/CMake/../../Sdk-1.4.0
Setting the version of the library to 0.2.1
-- Configuring done
CMake Error at CMakeLists.txt:121 (add_library):
  Cannot find source file:

    /app/build/boost_1_67_0/libs/system/src/error_code.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: CMake can not determine linker language for target: OrthancS3StoragePlugin
CMake Error: Cannot determine link language for target "OrthancS3StoragePlugin".
-- Generating done
-- Build files have been written to: /app/build
cmake error.

```

I haven't resolved it yet, I plan to be transparent and publish my efforts to install the plugin in this thread. I figure since the project is young and the installation process is untested, I could be used as a test case to improving the installation process for future users. So pardon me if I err on the side of overcommunication and it ends up looking more like a tech blog. 


Upon closer inspection it seems that I am building a docker file that would have been used to build the s3 plugin. I assume the purpose of building the plugin in a Dockerfile is so that the building process can be done in the same environment independently of who is building it. But the environment dependency is merely transferred to the building of the docker environment :s . A good solution would be to publish the built docker container directly (perhaps with the plugin already built, but at this point it would be better to release the built plugin). I searched dockerhub and found nothing, so it seems I'll have to solve this issue:
https://hub.docker.com/search?q=orthanc%20s3&type=image
https://hub.docker.com/search?q=radpoint&type=image

Before trying to resolve this issue, I found an alternative script to build this locally:

https://github.com/radpointhq/orthanc-s3-storage/blob/master/scripts/docker-build-orthanc/build-s3-plugin.sh

But I immediately encountered the following error.

`Uncompressing: /home/tomas/Projects/jcimagenes/orthanc-s3-plugin/orthanc-s3-storage/ThirdPartyDownloads/Orthanc-1.4.0.tar.gz
-- Found PythonInterp: /usr/bin/python (found version "2.7.15") 
-- Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR) 
CMake Error at build/Orthanc-1.4.0/Resources/CMake/LibCurlConfiguration.cmake:321 (message):
  Unable to find LibCurl
Call Stack (most recent call first):
  build/Orthanc-1.4.0/Resources/CMake/OrthancFrameworkConfiguration.cmake:221 (include)
  CMakeLists.txt:57 (include)
`

Curl is installed, but based on the error message, I am assuming that I am supposed to set some env variables (CURL_LIBRARY CURL_INCLUDE_DIR) to specify its path. This is undocumented, so if I choose to pursue this path, I'm imagining I am going to have to read the CMAKE file and negotiate other configurations. I'm going to switch back to installing through docker.

I'm going to ssh into the docker after the cmake fails and try to figure out what went wrong. I cannot be sure whether there was a problem when building the docker image (an environment difference) , or when running the docker image (a flat out unconditional bug.) Regardless of whether publishing the container image would have avoided this bug, it would certainly have narrowed down the possiblities.

I'll be back

**Comment by TZubiri** [comment]
Managed to build succesfully on an ec2 t3.medium instance. The slow internet connection must have been responsible for some side effect inside the container.

**Comment by kwach** [comment]
```
CMake Error: CMake can not determine linker language for target: OrthancS3StoragePlugin
```
That I have never seen.

Good to hear you managed to build it. 
Using `clang` we encountered much less problems compared to `gcc`.

I'm open to PR's making this whole thing better ;)

**Comment by kwach** [comment]
I've never had to set `CURL_INCLUDE_DIR`. It's enough to have the dev package installed on the OS (as AWS SDK takes it from OS so they match)

**Comment by TZubiri** [comment]
I'm encountering an error when loading the plugin from Orthanc. Here is the output, I highlighted the most relevant aspects.

```
**W0308 16:03:43.101761 main.cpp:700] Loading plugin(s) from: /usr/share/orthanc/plugins**
W0308 16:03:43.113673 PluginsManager.cpp:269] Registering plugin 'dicom-web' (version 0.6)
W0308 16:03:43.113888 PluginsManager.cpp:168] URI to the DICOMweb REST API: /dicom-web/
W0308 16:03:43.114076 PluginsManager.cpp:168] URI to the WADO-URI API: /wado
W0308 16:03:43.126667 PluginsManager.cpp:269] Registering plugin 'osimis-web-viewer' (version 1.2.0.0-0d4bfbd5)
W0308 16:03:43.126726 PluginsManager.cpp:168] Initializing the Web viewer
W0308 16:03:43.127038 PluginsManager.cpp:168] Using GDCM instead of the DICOM decoder that is built in Orthanc
**E0308 16:03:43.127519 SharedLibrary.cpp:75] dlopen(/usr/share/orthanc/plugins/libOrthancS3StoragePlugin.so) failed: Error libaws-cpp-sdk-s3.so: cannot open shared object file: No such file or directory**
W0308 16:03:43.127657 PluginsManager.cpp:219] Unregistering plugin 'dicom-web' (version 0.6)
W0308 16:03:43.130513 PluginsManager.cpp:219] Unregistering plugin 'osimis-web-viewer' (version 1.2.0.0-0d4bfbd5)
W0308 16:03:43.130536 PluginsManager.cpp:168] Finalizing the Web viewer
**E0308 16:03:43.135112 main.cpp:1462] Uncaught exception, stopping now: [Error while using a shared library (plugin)] (code 25)**
W0308 16:03:43.137647 main.cpp:1495] Orthanc has stopped
```

The key error is this one: 

`**E0308 16:03:43.127519 SharedLibrary.cpp:75] dlopen(/usr/share/orthanc/plugins/libOrthancS3StoragePlugin.so) failed: Error libaws-cpp-sdk-s3.so: cannot open shared object file: No such file or directory**`

The file exists, as evidenced by the fact that it is referred to in the output, while it was unspecified in the configuration files (plugins were loaded by folder)

File permissions of the working plugins are the same as the s3 one.

@kwach Could you upload a compiled .so file so I can rule out whether it is a build issue? That would help greatly with troubleshooting. Thank you.

I'm uploading my own binary as well.

[libOrthancS3StoragePlugin.zip](https://github.com/radpointhq/orthanc-s3-storage/files/2946673/libOrthancS3StoragePlugin.zip)

**Comment by kwach** [comment]
Plugin build is fixed for dynamic linking. Otherwise I had issues with `curl` and was unable to fix it at that time.

There are couple of libs in plugin deps. Mainly it's AWS SDK.

The error itself say about missing `libaws-cpp-sdk-s3.so` while loading `libOrthancS3StoragePlugin.so`

CMake `make install` creates the desired structure and sets `rpath` relative to the plugin lib, afair.
You need to copy the whole tree, not only the plugin.

Does this happen when you manually build? I assume yes

**Comment by TZubiri** [comment]
> Plugin build is fixed for dynamic linking. Otherwise I had issues with `curl` and was unable to fix it at that time.
> 
> There are couple of libs in plugin deps. Mainly it's AWS SDK.
> 
> The error itself say about missing `libaws-cpp-sdk-s3.so` while loading `libOrthancS3StoragePlugin.so`
Oh, silly me, I thought it was an error in cpp-sdk and libOrthancS3StoragePlugin was not found.

> Does this happen when you manually build? I assume yes
I am building using the scripts provided in the source code. The manual part I am doing is transferring the plugin files to an osimis-pro docker image.

> CMake `make install` creates the desired structure and sets `rpath` relative to the plugin lib, afair.
> You need to copy the whole tree, not only the plugin.
> 
This was it! I imported the libaws and libcurl plugins into the orthanc/lib directory. I had to change my working directory to this folder in order to get it to work though. 

Then I got the following error:

`W0311 23:57:14.457556 PluginsManager.cpp:269] Registering plugin 's3-storage' (version 1.4.0-0.2.1)
W0311 23:57:14.457591 PluginsManager.cpp:168] [S3] Storage plugin is initializing
W0311 23:57:14.457714 PluginsManager.cpp:168] StorageDir and IndexDir were not set.
`

This was solved by setting this in my  orthanc.json config file:
`  "StorageDirectory": "OrthancStorage",
  "IndexDirectory": "OrthancStorage"`

And finally, I was able to hit what looks like the same issue as this https://github.com/radpointhq/orthanc-s3-storage/issues/2#issuecomment-466168260_

`I0312 00:37:52.925249 PluginsManager.cpp:172] [S3] Aws Access Key set
I0312 00:37:52.925263 PluginsManager.cpp:172] [S3] Aws Secret Key set
I0312 00:37:52.925281 PluginsManager.cpp:172] [S3] Aws region: us-east-1
I0312 00:37:52.925290 PluginsManager.cpp:172] [S3] Aws bucket: jc-imagenes-medicas2
I0312 00:37:52.925305 PluginsManager.cpp:172] [S3] S3Direct
I0312 00:37:52.925757 PluginsManager.cpp:172] [S3] Using credentials from the config file
I0312 00:37:52.925923 PluginsManager.cpp:172] [S3] Checking bucket: jc-imagenes-medicas2
E0312 00:38:23.538110 PluginsManager.cpp:164] [S3] Create Bucket error:  Unable to connect to endpoint
E0312 00:38:23.538241 PluginsManager.cpp:102] Error while initializing plugin /usr/share/orthanc/plugins/libOrthancS3StoragePlugin.so (code 1)
W0312 00:38:23.542011 PluginsManager.cpp:219] Unregistering plugin 'dicom-web' (version 0.6)
W0312 00:38:23.557735 PluginsManager.cpp:219] Unregistering plugin 'osimis-web-viewer' (version 1.2.0.0-0d4bfbd5)
W0312 00:38:23.557889 PluginsManager.cpp:168] Finalizing the Web viewer
E0312 00:38:23.574508 main.cpp:1462] Uncaught exception, stopping now: [Error while using a shared library (plugin)] (code 25)
`
Not sure how I could solve this without debugging the C code. My next alternatives are to use Orthanc Jobs, or try the Azure plugin.

I'm leaving this todo list here, I might come back to implement one in the future:

- [ ] Further build automation.

- [ ] Help release Binaries

- [ ] Fix "Unable to connect to endpoint problem" 

- [ ] Add connection check before creating bucket to get cleaner error message.

Let me know if you need
Thank you.

**Comment by kwach** [comment]
Are you sure you have AWS permissions to access the bucket? I would test this with aws cli just to be sure

M.

**Comment by TZubiri** [comment]
Yes, I can use these credentials to access from the host OS. They are root credentials, so they should have permissions to create buckets.

Couple of questions:
- I tried exposing ports 80, 443, and using --network host. But there was no success. How is docker supposed tknow how to redirect requests made by libaws to the outside world?
- Should the bucket be created beforehand or will the plugin create it? ( I tried both possiblities)
- the format for the s3-bucket option should be just the bucket name right? Not a HTTP or S3 url.
- Here is my config file, just in case:
`{
  "AuthenticationEnabled": true,
  "RemoteAccessAllowed": true,
  "RegisteredUsers": {
    "admin": "redacted password"
  },
  "S3": {
    "aws_access_key_id": "redacted root public key",
    "aws_secret_access_key": "redacted root secret key",
    "aws_region": "us-east-1",
    "s3_bucket": "jc-imagenes-medicas33",
    "implementation": "direct"
  },
  "Plugins": [
    "/usr/share/orthanc/plugins"
  ],

  "StorageDirectory": "OrthancStorage",
  "IndexDirectory": "OrthancStorage"
}
`

**Comment by bpycinski** [comment]
Hi @TZubiri, we currently have met the same issue (`Unable to connect to endpoint`) inside the Docker container. But, if an instance of Orthanc run directly on host Ubuntu 16.04, then the connection to S3 is fine. On the other hand, if the plugin was linked to dummy hello-world program inside docker, it also has connected properly. Only inside `osimis/orthanc` image there are these issues. I suspect they depends on linker's problem with libcurl and openssl. 

We are still looking for the solution, our temporary workaround is not to use official Docker image.

**Comment by TZubiri** [comment]
Thank you for that contribution! That narrows it down quite a bit. I'll play around a bit with docker images, and if I can't fix it, I'll use the workaround.

Regards!

**Comment by TZubiri** [comment]
I was just making a Lua script to forward studies in between Orthanc servers and I was just wondering:
@kwach Did you consider making this service as a Lua script? What made you go for the C++ plugin?

Thank you.

**Comment by rubensmg** [comment]
Hello everyone, i made an workaround to use on this on docker image (I don't use the official image). If you don't pass the `aws_region`, the error `Unable to connect to endpoint` is not displayed, but the bucket is created in Frankfurt region.
Apparently everything works fine, but i'm still looking how to fix this for create my bucket in Virginia Region.

I'm using Ubuntu Xenial Image and AWS Fargate.

**Comment by TZubiri** [comment]
No such luck for me :(

> Hello everyone, i made an workaround to use on this on docker image (I don't use the official image). If you don't pass the `aws_region`, the error `Unable to connect to endpoint` is not displayed, but the bucket is created in Frankfurt region.
> Apparently everything works fine, but i'm still looking how to fix this for create my bucket in Virginia Region.
> 
> I'm using Ubuntu Xenial Image and AWS Fargate.



> Hello everyone, i made an workaround to use on this on docker image (I don't use the official image). If you don't pass the `aws_region`, the error `Unable to connect to endpoint` is not displayed, but the bucket is created in Frankfurt region.
> Apparently everything works fine, but i'm still looking how to fix this for create my bucket in Virginia Region.
> 
> I'm using Ubuntu Xenial Image and AWS Fargate.

No such luck for me:

`I0314 15:40:59.796825 PluginsManager.cpp:172] [S3] Aws region: eu-central-1
I0314 15:40:59.796840 PluginsManager.cpp:172] [S3] Aws bucket: jc-imagenes-medicas33
I0314 15:40:59.796868 PluginsManager.cpp:172] [S3] S3Direct
I0314 15:40:59.797314 PluginsManager.cpp:172] [S3] Using credentials from the config file
I0314 15:40:59.797480 PluginsManager.cpp:172] [S3] Checking bucket: jc-imagenes-medicas33
E0314 15:41:33.238041 PluginsManager.cpp:164] [S3] Create Bucket error:  Unable to connect to endpoint
`

If this worked for you, you could try rebuilding and changing the default region at https://github.com/radpointhq/orthanc-s3-storage/blob/master/src/Plugin.cpp#L37

While you are at it you could try to debug something (even if it is by adding some prints) to figure out what's going on.

Here are the relevant lines:
https://github.com/radpointhq/orthanc-s3-storage/blob/master/src/S3ops.cpp#L106
https://github.com/radpointhq/orthanc-s3-storage/blob/master/src/S3ops.cpp#L85

I would use the native logger to print the variables involved in the previous lines like this: https://github.com/radpointhq/orthanc-s3-storage/blob/4a5afb69e723efcb086ae91bf1a9c3ea6964d76f/src/Plugin.cpp#L248

Good luck!

**Comment by bpycinski** [comment]
Hello, neither I did have a success with different bucket's locations. 

But I was able to fetch logs of aws. Had to change default log level to `Trace`:
https://github.com/radpointhq/orthanc-s3-storage/blob/40da488d531da7ccf55d8e9ab0214de5030e0eaf/src/S3ops.cpp#L62

Then after overriding `entrypoint` to bash and runnig Orthanc manually, the following errors appear. It is created in root filesystem as `aws_sdk_date.log`. The most important line is probably:
> [ERROR] 2019-03-15 12:49:49 CurlHttpClient [139827526346560] Curl returned error code 60 - Peer certificate cannot be authenticated with given CA certificates

I have repeated the error with differenf SSL flavours (GNUTLS, OpenSSL), with various versions of curl. Package `ca-certificates` was reinstalled, valid default file `/etc/ssl/certs/ca-certificates.crt` exists. An executable `curl` connects to ssl servers without problems, so it is rathes some kind of AWS problem. But I have not figure it out.

> [TRACE] 2019-03-15 12:49:49 AWSClient [139827526346560] Found body, but content-length has not been set, attempting to compute content-length
> [DEBUG] 2019-03-15 12:49:49 AWSAuthV4Signer [139827526346560] Note: Http payloads are not being signed. signPayloads=0 http scheme=https
> [DEBUG] 2019-03-15 12:49:49 AWSAuthV4Signer [139827526346560] Canonical Header String: content-length:185
> content-type:application/xml
> host:s3.eu-central-1.amazonaws.com
> x-amz-api-version:2006-03-01
> x-amz-content-sha256:UNSIGNED-PAYLOAD
> x-amz-date:20190315T124949Z
> 
> [DEBUG] 2019-03-15 12:49:49 AWSAuthV4Signer [139827526346560] Signed Headers value:content-length;content-type;host;x-amz-api-version;x-amz-content-sha256;x-amz-date 
> [DEBUG] 2019-03-15 12:49:49 AWSAuthV4Signer [139827526346560] Canonical Request String: PUT
> /name-of-my-bucket
> 
> content-length:185
> content-type:application/xml
> host:s3.eu-central-1.amazonaws.com
> x-amz-api-version:2006-03-01
> x-amz-content-sha256:UNSIGNED-PAYLOAD
> x-amz-date:20190315T124949Z
> 
> content-length;content-type;host;x-amz-api-version;x-amz-content-sha256;x-amz-date
> UNSIGNED-PAYLOAD
> [DEBUG] 2019-03-15 12:49:49 AWSAuthV4Signer [139827526346560] Final String to sign: AWS4-HMAC-SHA256
> 20190315T124949Z
> 20190315/eu-central-1/s3/aws4_request
> 87efXXXXXXXXXXXX9b254
> [DEBUG] 2019-03-15 12:49:49 AWSAuthV4Signer [139827526346560] Final computed signing hash: 427ccc9XXXXXXXXXXXXXXXXXX232ea85a8c81d
> [DEBUG] 2019-03-15 12:49:49 AWSAuthV4Signer [139827526346560] Signing request with: AWS4-HMAC-SHA256 Credential=AWS-ACCESS-KEY/20190315/eu-central-1/s3/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-api-version;x-amz-content-sha256;x-amz-date, Signature=427ccc9eXXXXXXXXXXXXXXXXXXXXXXXea85a8c81d
> [DEBUG] 2019-03-15 12:49:49 AWSClient [139827526346560] Request Successfully signed
> [TRACE] 2019-03-15 12:49:49 CurlHttpClient [139827526346560] Making request to https://s3.eu-central-1.amazonaws.com/bucket-name
> [TRACE] 2019-03-15 12:49:49 CurlHttpClient [139827526346560] Including headers: 
> [TRACE] 2019-03-15 12:49:49 CurlHttpClient [139827526346560] authorization: AWS4-HMAC-SHA256 Credential=AWS-ACCESS-KEY/20190315/eu-central-1/s3/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-api-version;x-amz-content-sha256;x-amz-date, Signature=427ccc9XXXXXXXXXXXXXXXXXXXXXXXXXX5a8c81d
> [TRACE] 2019-03-15 12:49:49 CurlHttpClient [139827526346560] content-length: 185
> [TRACE] 2019-03-15 12:49:49 CurlHttpClient [139827526346560] content-type: application/xml
> [TRACE] 2019-03-15 12:49:49 CurlHttpClient [139827526346560] host: s3.eu-central-1.amazonaws.com
> [TRACE] 2019-03-15 12:49:49 CurlHttpClient [139827526346560] user-agent: aws-sdk-cpp/1.7.28 Linux/4.15.0-46-generic x86_64 GCC/5.4.0
> [TRACE] 2019-03-15 12:49:49 CurlHttpClient [139827526346560] x-amz-api-version: 2006-03-01
> [TRACE] 2019-03-15 12:49:49 CurlHttpClient [139827526346560] x-amz-content-sha256: UNSIGNED-PAYLOAD
> [TRACE] 2019-03-15 12:49:49 CurlHttpClient [139827526346560] x-amz-date: 20190315T124949Z
> [DEBUG] 2019-03-15 12:49:49 CurlHandleContainer [139827526346560] Attempting to acquire curl connection.
> [INFO] 2019-03-15 12:49:49 CurlHandleContainer [139827526346560] Connection has been released. Continuing.
> [DEBUG] 2019-03-15 12:49:49 CurlHandleContainer [139827526346560] Returning connection handle 0x1687f70
> [DEBUG] 2019-03-15 12:49:49 CurlHttpClient [139827526346560] Obtained connection handle 0x1687f70
> [ERROR] 2019-03-15 12:49:49 CurlHttpClient [139827526346560] Curl returned error code 60 - Peer certificate cannot be authenticated with given CA certificates
> [DEBUG] 2019-03-15 12:49:49 CurlHandleContainer [139827526346560] Releasing curl handle 0x1687f70
> [DEBUG] 2019-03-15 12:49:49 CurlHandleContainer [139827526346560] Notified waiting threads.
> [DEBUG] 2019-03-15 12:49:49 AWSClient [139827526346560] Request returned error. Attempting to generate appropriate error codes from response 
> [ERROR] 2019-03-15 12:49:49 AWSClient [139827526346560] HTTP response code: 23574256
> Exception name:  
> Error message: Unable to connect to endpoint
> 0 response headers:
> [WARN] 2019-03-15 12:49:49 AWSClient [139827526346560] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
> [DEBUG] 2019-03-15 12:49:49 AWSClient [139827526346560] Date header was not found in the response, can't attempt to detect clock skew

**Comment by capedcrusader8510** [comment]
Hey guys, anyone managed to get around the 'Unable to connect to endpoint' issue yet ?

**Comment by gabrielHosino** [comment]
Hi, I'm having the same issue. Any updates on that?

**Comment by hung084** [comment]
I found a solution for "Unable to connect to endpoint" issue. If you are certain that all your bucket policies are correct. Add the following line to the S3Impl::ConfigureAwsSdk() method in S3ops.cpp:

```
aws_client_config.scheme = Aws::Http::Scheme::HTTPS;
aws_client_config.connectTimeoutMs = 30000;
aws_client_config.requestTimeoutMs = 600000;
aws_client_config.caPath = Aws::String("/etc/ssl/certs/");
```
If you have a specific ca file, you can replace the caPath with this:
`aws_client_config.caFile = Aws::String("/path/to/ca-file");`

Also, if you are using "us-east-1" as your region, there will probably be a bug for InvalidLocationConstraint as "us-east-1" is a default location and you don't need to SetLocationConstraint for it. So add this line of codes after SetBucket() in the same ConfigureAwsSdk() function:

```
request.SetBucket(_bucket_name);
Aws::S3::Model::CreateBucketConfiguration req_config;
auto regionConstraint = Aws::S3::Model::BucketLocationConstraintMapper::GetBucketLocationConstraintForName(s3_region.c_str());
if (regionConstraint != Aws::S3::Model::BucketLocationConstraint::us_east_1)
{
     req_config.SetLocationConstraint(regionConstraint);
}
```

**Comment by TZubiri** [comment]
In the end, my solution was not to use the plugin.

**Comment by bpycinski** [comment]
Hello @hung084 ! Thank you very much for your post. Indeed, it solves the connection issue. Would you mind committing a pull request for this issue?

**Comment by bpycinski** [comment]
Thanks to @hung084's contribution, the solution was found.
